// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import localFont from "next/font/local";
// import Navbar from "@/components/Navbar";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});



export const metadata: Metadata = {
  metadataBase: new URL('https://alvinpratama.com'),
  title: {
    default: 'Alvin Pratama',
    template: '%s | Alvin Pratama',
  },
  description: 'Software Engineer',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  twitter: {
    title: 'Alvin Pratama',
  },
}

interface RootLayout {
  children: React.ReactNode;
  params: {
    locale: string;
  }
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<RootLayout>) {
  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      lang={locale}>
      <body>
        <main className='mx-auto flex min-h-screen max-w-[1280px] flex-col flex-wrap gap-10 px-6 md:py-12 py-4 md:gap-16'>
          {/* <Navbar /> */}
          {children}
          {/* <Footer /> */}
        </main>
      </body>
    </html>
  );
}
